import Head from "next/head";
import React from "react";
import { Container } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>Chess learn coordinates</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="sm">
        <span>hello world</span>
      </Container>
    </>
  );
}
